package com.zdj.web.mapper;

import com.zdj.web.pojo.Banks;
import com.zdj.web.pojo.BanksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BanksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    long countByExample(BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    int deleteByExample(BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    int insert(Banks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    int insertSelective(Banks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    List<Banks> selectByExample(BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    Banks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Banks record, @Param("example") BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    int updateByExample(@Param("record") Banks record, @Param("example") BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    int updateByPrimaryKeySelective(Banks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    int updateByPrimaryKey(Banks record);
}