package com.zdj.web.pojo;

import java.util.Date;

public class Alreadybuy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.good_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.user_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.address_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.good_count
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer goodCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.pay
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.state
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alreadybuy.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.id
     *
     * @return the value of alreadybuy.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.id
     *
     * @param id the value for alreadybuy.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.good_id
     *
     * @return the value of alreadybuy.good_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.good_id
     *
     * @param goodId the value for alreadybuy.good_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.user_id
     *
     * @return the value of alreadybuy.user_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.user_id
     *
     * @param userId the value for alreadybuy.user_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.address_id
     *
     * @return the value of alreadybuy.address_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.address_id
     *
     * @param addressId the value for alreadybuy.address_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.good_count
     *
     * @return the value of alreadybuy.good_count
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getGoodCount() {
        return goodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.good_count
     *
     * @param goodCount the value for alreadybuy.good_count
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setGoodCount(Integer goodCount) {
        this.goodCount = goodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.pay
     *
     * @return the value of alreadybuy.pay
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.pay
     *
     * @param pay the value for alreadybuy.pay
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setPay(Integer pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.state
     *
     * @return the value of alreadybuy.state
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.state
     *
     * @param state the value for alreadybuy.state
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.create_time
     *
     * @return the value of alreadybuy.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.create_time
     *
     * @param createTime the value for alreadybuy.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.create_user
     *
     * @return the value of alreadybuy.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.create_user
     *
     * @param createUser the value for alreadybuy.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.update_time
     *
     * @return the value of alreadybuy.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.update_time
     *
     * @param updateTime the value for alreadybuy.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.update_user
     *
     * @return the value of alreadybuy.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.update_user
     *
     * @param updateUser the value for alreadybuy.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alreadybuy.is_delete
     *
     * @return the value of alreadybuy.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alreadybuy.is_delete
     *
     * @param isDelete the value for alreadybuy.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}