package com.zdj.web.pojo;

import java.util.Date;

public class Banks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.id
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.name
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.label
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.style
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.level
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.create_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.create_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.update_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.update_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banks.is_delete
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.id
     *
     * @return the value of banks.id
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.id
     *
     * @param id the value for banks.id
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.name
     *
     * @return the value of banks.name
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.name
     *
     * @param name the value for banks.name
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.label
     *
     * @return the value of banks.label
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.label
     *
     * @param label the value for banks.label
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.style
     *
     * @return the value of banks.style
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.style
     *
     * @param style the value for banks.style
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.level
     *
     * @return the value of banks.level
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.level
     *
     * @param level the value for banks.level
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.create_time
     *
     * @return the value of banks.create_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.create_time
     *
     * @param createTime the value for banks.create_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.create_user
     *
     * @return the value of banks.create_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.create_user
     *
     * @param createUser the value for banks.create_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.update_time
     *
     * @return the value of banks.update_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.update_time
     *
     * @param updateTime the value for banks.update_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.update_user
     *
     * @return the value of banks.update_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.update_user
     *
     * @param updateUser the value for banks.update_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banks.is_delete
     *
     * @return the value of banks.is_delete
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banks.is_delete
     *
     * @param isDelete the value for banks.is_delete
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}