package com.zdj.web.pojo;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.big_type
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer bigType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.small_type
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer smallType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.count
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_down
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Byte isDown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.big_type
     *
     * @return the value of goods.big_type
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getBigType() {
        return bigType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.big_type
     *
     * @param bigType the value for goods.big_type
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setBigType(Integer bigType) {
        this.bigType = bigType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.small_type
     *
     * @return the value of goods.small_type
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getSmallType() {
        return smallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.small_type
     *
     * @param smallType the value for goods.small_type
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setSmallType(Integer smallType) {
        this.smallType = smallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.count
     *
     * @return the value of goods.count
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.count
     *
     * @param count the value for goods.count
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_down
     *
     * @return the value of goods.is_down
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Byte getIsDown() {
        return isDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_down
     *
     * @param isDown the value for goods.is_down
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setIsDown(Byte isDown) {
        this.isDown = isDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_user
     *
     * @return the value of goods.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_user
     *
     * @param createUser the value for goods.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_user
     *
     * @return the value of goods.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_user
     *
     * @param updateUser the value for goods.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_delete
     *
     * @return the value of goods.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_delete
     *
     * @param isDelete the value for goods.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}