package com.zdj.web.pojo;

import java.util.Date;

public class Headgood {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.good_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.comment
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headgood.picture_path
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String picturePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.id
     *
     * @return the value of headgood.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.id
     *
     * @param id the value for headgood.id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.good_id
     *
     * @return the value of headgood.good_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.good_id
     *
     * @param goodId the value for headgood.good_id
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.comment
     *
     * @return the value of headgood.comment
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.comment
     *
     * @param comment the value for headgood.comment
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.create_time
     *
     * @return the value of headgood.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.create_time
     *
     * @param createTime the value for headgood.create_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.create_user
     *
     * @return the value of headgood.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.create_user
     *
     * @param createUser the value for headgood.create_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.update_time
     *
     * @return the value of headgood.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.update_time
     *
     * @param updateTime the value for headgood.update_time
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.update_user
     *
     * @return the value of headgood.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.update_user
     *
     * @param updateUser the value for headgood.update_user
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.is_delete
     *
     * @return the value of headgood.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.is_delete
     *
     * @param isDelete the value for headgood.is_delete
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headgood.picture_path
     *
     * @return the value of headgood.picture_path
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headgood.picture_path
     *
     * @param picturePath the value for headgood.picture_path
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }
}