package com.zdj.web.pojo;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.type
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.priority
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.hot
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Byte hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.update_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.update_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.is_delete
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.type
     *
     * @return the value of news.type
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.type
     *
     * @param type the value for news.type
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.priority
     *
     * @return the value of news.priority
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.priority
     *
     * @param priority the value for news.priority
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.hot
     *
     * @return the value of news.hot
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Byte getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.hot
     *
     * @param hot the value for news.hot
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setHot(Byte hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.create_time
     *
     * @return the value of news.create_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.create_time
     *
     * @param createTime the value for news.create_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.create_user
     *
     * @return the value of news.create_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.create_user
     *
     * @param createUser the value for news.create_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.update_time
     *
     * @return the value of news.update_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.update_time
     *
     * @param updateTime the value for news.update_time
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.update_user
     *
     * @return the value of news.update_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.update_user
     *
     * @param updateUser the value for news.update_user
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.is_delete
     *
     * @return the value of news.is_delete
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.is_delete
     *
     * @param isDelete the value for news.is_delete
     *
     * @mbg.generated Fri Apr 27 16:10:06 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}