package com.zdj.web.pojo;

public class NewsWithBLOBs extends News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.picture_path
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String picturePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.contain
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    private String contain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.picture_path
     *
     * @return the value of news.picture_path
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.picture_path
     *
     * @param picturePath the value for news.picture_path
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.contain
     *
     * @return the value of news.contain
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public String getContain() {
        return contain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.contain
     *
     * @param contain the value for news.contain
     *
     * @mbg.generated Wed Apr 25 18:08:55 CST 2018
     */
    public void setContain(String contain) {
        this.contain = contain == null ? null : contain.trim();
    }
}