package com.zdj.web.pojo;

import java.util.Date;

public class Shopcar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.good_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.user_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.address_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.good_count
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Integer goodCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.state
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.create_time
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.create_user
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.update_time
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.update_user
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopcar.is_delete
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.id
     *
     * @return the value of shopcar.id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.id
     *
     * @param id the value for shopcar.id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.good_id
     *
     * @return the value of shopcar.good_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.good_id
     *
     * @param goodId the value for shopcar.good_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.user_id
     *
     * @return the value of shopcar.user_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.user_id
     *
     * @param userId the value for shopcar.user_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.address_id
     *
     * @return the value of shopcar.address_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.address_id
     *
     * @param addressId the value for shopcar.address_id
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.good_count
     *
     * @return the value of shopcar.good_count
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Integer getGoodCount() {
        return goodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.good_count
     *
     * @param goodCount the value for shopcar.good_count
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setGoodCount(Integer goodCount) {
        this.goodCount = goodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.state
     *
     * @return the value of shopcar.state
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.state
     *
     * @param state the value for shopcar.state
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.create_time
     *
     * @return the value of shopcar.create_time
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.create_time
     *
     * @param createTime the value for shopcar.create_time
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.create_user
     *
     * @return the value of shopcar.create_user
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.create_user
     *
     * @param createUser the value for shopcar.create_user
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.update_time
     *
     * @return the value of shopcar.update_time
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.update_time
     *
     * @param updateTime the value for shopcar.update_time
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.update_user
     *
     * @return the value of shopcar.update_user
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.update_user
     *
     * @param updateUser the value for shopcar.update_user
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopcar.is_delete
     *
     * @return the value of shopcar.is_delete
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopcar.is_delete
     *
     * @param isDelete the value for shopcar.is_delete
     *
     * @mbg.generated Thu Apr 19 00:34:54 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}